default_install_hook_types:
  - commit-msg
  - pre-commit

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 5f9c312d9978fbcee1da97154ba385834eeda799 # v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/rhysd/actionlint
    rev: 03d0035246f3e81f36aed592ffb4bebf33a03106 # v1.7.7
    hooks:
      - id: actionlint-system

  - repo: https://github.com/doughom/pre-commit-hooks
    rev: v0.1.0
    hooks:
      - id: prettier
      - id: shellcheck
      - id: shfmt
