name: Lint

on:
  workflow_dispatch:
  pull_request:

permissions: {}

env:
  VALIDATE_BIOME_FORMAT: false
  VALIDATE_JSCPD: false
  # textlint does not ignore when passed file paths: https://github.com/textlint/textlint/issues/1408
  VALIDATE_NATURAL_LANGUAGE: false

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super Linter
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 #v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
