name: Lint

on:
  workflow_dispatch:
  pull_request:

permissions: {}

env:
  VALIDATE_JSCPD: false
  # textlint does not ignore when passed file paths
  # https://github.com/textlint/textlint/issues/1408
  VALIDATE_NATURAL_LANGUAGE: false

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2 #v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
