name: "Release Features And Generate Docs"
on:
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Publish Features"
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docs PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config pull.rebase false
          git config push.autoSetupRemote true
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git switch -c "docs-auto-update-$GITHUB_RUN_ID"
          git add "*/**/README.md"
          message="docs: auto update [skip ci]"
          if git commit -m "$message"; then
            git push
            gh pr create --title "$message" --body "$message"
          fi
